branches:
  only:
    - master
addons:
  postgresql: '9.3'
before_install:
- sudo add-apt-repository -y ppa:moti-p/cc
- sudo apt-get update
- sudo apt-get -y --reinstall install imagemagick
- sudo apt-get install libpq-dev
- sudo apt-get install postgresql-9.3 postgresql-server-dev-9.3 libpq-dev
- bundle config build.libv8 --with-system-v8
before_script:
- psql -c "create database travis_ci_test;" -U postgres
- sudo pip install boto
language: ruby
rvm: 2.0.0
script: bundle exec rspec specs/
notifications:
  slack:
    secure: miw9kyiWMkpyOPyrmeoBLNvloWNlFAUWZ5To4X6Wqfv6TJezy8w0ZopnWj+ZkaqEIeOoUk75+Gx/EtdIMkhljS49fXIbUKu+qd17VjUHCrszJZN4kzq7ovJ7UiXp7awJZLy3ArSQtkDxCmIr089c6PnRi4Iyn0jV48AQeB6F/ek=
branches:
  only:
  - master
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: InKGOprXIbkhJh1QmZ2q7wV6aoy2NnzSqgirSJaIBTUsp+kC4vATMrhpJCQP5W1AjLkpj7lt7p8AIwXy9JCYcwaPAjLOQVKgMYFMvWbpBw0/1RywnsUSF/ArSxi1Q56oBF5L6JfpkQEAq0DsCVpUf2TeYa9DMInVJ863EkxxlXA=
  - secure: lnpRMyk9YGDQwUM6VRmtp4kGGTfVngGzKIBbCswYWdhlrBwr4TCueYtDhvqNbBvqn0BEHHGn5Ws/MjxPiERvV7UG0FZPE/1W9mg+ekbqAkG+8ToXXgKVm8UJFzwTvFrYnGjM1zS5V5biuicKs8A53YUaZXMsI46lTtKjztGlq38=
  - secure: YoAAxECojo1bpvHY82Z9dVPlPqCfgmPSpBIwNNi/IPc008UEArFow60KYrlJBi7DhHyF0DpSLnE41uIqRUmzB9unt9R8StnNKF7Zc5sZKznjRbXK6lx9Y7k+91TZbNc7k/ZzDtWaqc+8BI1WFtuZd3lyjr0rKi65czYwG0fDnoU=
after_success:
- wget "https://s3.amazonaws.com/elasticbeanstalk/cli/AWS-ElasticBeanstalk-CLI-2.6.1.zip"
- unzip "AWS-ElasticBeanstalk-CLI-2.6.1.zip"
- AWS-ElasticBeanstalk-CLI-2.6.1/AWSDevTools/Linux/AWSDevTools-RepositorySetup.sh
- mkdir .elasticbeanstalk
- sudo echo "[global]" >> .elasticbeanstalk/config
- sudo echo "AwsCredentialFile=/Users/travis/.elasticbeanstalk/aws_credential_file"
  >> .elasticbeanstalk/config
- sudo echo "ApplicationName=cukebot" >> .elasticbeanstalk/config
- sudo echo "DevToolsEndpoint=git.elasticbeanstalk.us-east-1.amazonaws.com" >> .elasticbeanstalk/config
- sudo echo "EnvironmentName=cukebot-prod-web-c1" >> .elasticbeanstalk/config
- sudo echo "Region=us-east-1" >> .elasticbeanstalk/config
- cat .elasticbeanstalk/confi
- cat ~/.elasticbeanstalk/aws_credential_file
- echo "us-east-1" | git aws.config
- echo -e "$AWS_ACCESS_KEY_ID\n$AWS_SECRET_ACCESS_KEY\n1\n\n\n1\n53\n2\nN\n1\n" | AWS-ElasticBeanstalk-CLI-2.6.1/eb/linux/python2.7/eb init
- git aws.push
