development:
  adapter: postgres
  host: localhost
  port: 5432
  user:
  password:
  database: cukebot
  
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  adapter: postgres
  host: <%= ENV["RDS_HOST"] %>
  port: <%= ENV["RDS_PORT"] %>
  user: <%= ENV["RDS_USER"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  database: <%= ENV["RDS_DB"] %>
